export const MINIMUM_COHORT_CUES = 20;
export const INCIDENT_FAILURE_THRESHOLD_PCT = 20;
export const COHORT_DISPERSION_THRESHOLD_PP = 15;
export const STITCHER_DEADLINE_MS = 450;
export const HARD_AUCTION_TIMEOUT_MS = 1200;
